### ISSUE TITLE
Questions on EDGE_NUM and PE_NUM.

### ISSUE THREAD

**Issue by AllFreven** [Xtra-Computing/ThunderGP#3]
Unless I'm misunderstanding, ThunderGP accesses EDGE_NUM edges and shuffles them to PE_NUM PEs in each cycle. 

Is there any reason that the number of PEs is set as twice as that of edges? 

Moreover, I also wonder whether the DRAM bandwidth can be fully utilized with 8 edges and 16 PEs since U200 provides up to 77GB/s bandwidth.

**Comment by HongshiTan** [comment]
Hi All Freven, 

For your first question: it is determined by the throughput,  PEs which is twice the number of edges can adequately process the incoming data, to be more details: the filter stage in each PEs have initiation interval (II) > 2  where the II of other compute modules is equal to 2 or less. Therefore, if we have the same number of PEs with the shuffle edges, the filter is the bottleneck of performance.

For your second question: U200 has __four__ memory channel, and we have __four__ Gather-Scatter compute units(CU) to connect with them. Each Gather-Scatter CU can fully utilize the bandwidth of one memory channel, here, one Gather-Scatter CUs have 16 PEs, so we can simply say there is 64 PEs in total.

**Comment by HongshiTan** [comment]
Let me know if you have another question.

**Comment by AllFreven** [comment]
Hi Hongshi,

Thanks a lot for your kindly reply, which dispels most of my doubts. 

I still have one minor question on the initiation interval. I find it hard to understand the meaning or usage of initiation interval in the architecture of ThunderGP. Can you kindly explain it in more detail?

**Comment by HongshiTan** [comment]
II is s the number of clock cycles between the start times of consecutive loop iterations for every pipelined function, and is an important parameter for performance. You can find more details from Xilinx guide book [ug902](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_1/ug902-vivado-high-level-synthesis.pdf)
